name: cheq_your_awesome_gallery
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.0
  data:
    path: ../data
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.0
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/

