name: cheq_your_awesome_gallery
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.0
  data:
    path: ../data
  device_info_plus: ^11.2.0
  domain:
    path: ../domain
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.0
  injectable: ^2.5.0
  permission_handler: ^11.3.1

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

