name: domain
description: "Domain layer"
version: 0.0.1

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
